// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMBr0sp8POasgQXGokPGVWpPhZ9v_S8cA',
    appId: '1:943275348123:web:ed115ade994741ad28b63e',
    messagingSenderId: '943275348123',
    projectId: 'eazymeals-56009',
    authDomain: 'eazymeals-56009.firebaseapp.com',
    storageBucket: 'eazymeals-56009.firebasestorage.app',
    measurementId: 'G-QX9CDBP7HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4UmNo39MOl0DrvoATEYs3paPVCwK81cE',
    appId: '1:943275348123:android:d231ae5c9fe8072728b63e',
    messagingSenderId: '943275348123',
    projectId: 'eazymeals-56009',
    storageBucket: 'eazymeals-56009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7wSqQZmaI7QnU-c3aQN8LNe3GMGXR_0M',
    appId: '1:943275348123:ios:14d134b25b01dc4828b63e',
    messagingSenderId: '943275348123',
    projectId: 'eazymeals-56009',
    storageBucket: 'eazymeals-56009.firebasestorage.app',
    androidClientId: '943275348123-rjqps3rns3hupovpm16tje2gugbu0p73.apps.googleusercontent.com',
    iosClientId: '943275348123-q1fp9ks7hatku4vc8f84orpfonr6khkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.abuTeaShop',
  );

}